### ISSUE TITLE
Ability to click on greyed out "Pause" button during presentation recording

### ISSUE THREAD

**Issue by collinmcrae** [dvoegeli/webmistc#16]
Found within the "Presentation" panel. Despite a "Cannot click" mouse cursor (circle with line through it) and a greyed out pause button the pause button is still clickable.

**Comment by KyleHoobler** [comment]
I'll look into it, and see if I can find the issue

**Comment by KyleHoobler** [comment]
```
toggleRecord(){
    const isRecording = !this.props.record_start;
    AppState.set('record_start', isRecording);
    Meteor.call('recordings.record', isRecording);
    isRecording ? AudioConference.startRecording() : AudioConference.stopRecording();
    }
```
It seems there should be a different method that does something similar to the recording button only specifically for the stop button that would make clicking this icon do nothing if not recording, and stop the function if it is in fact recording. This is in webmistc/imports/ui/app/components/features/Presentation.jsx

**Comment by dvoegeli** [comment]
Thanks, Kyle! I really appreciate you helping out with WebMISTC! 

You're approach is very good, but also very close. Few suggestions:
- follow established naming conventions (e.g., togglePause)
- toggle the pause button (in the css, button switches between play/pause icons) 
- make code DRY (wrap current toggle function inside new function, with guard statement at the top)
