### ISSUE TITLE
Turning Sticky notes off disables ability to apply multiple tools

### ISSUE THREAD

**Issue by AlexisRamer** [dvoegeli/webmistc#39]
When you turn StickyNotes off using the switch, if you use a tool like pencil arrow or text box what you did only remains on the screen until you try to use another tool on the screen. I used the tools on the side with Sticky notes on and then I turned Sticky notes and drew a line using the pencil tool. Then when I clicked on the arrow tool and when I made an arrow the line I had drawn before disappeared. The same happened when I tried with any of the other drawing tools.

**Comment by dvoegeli** [comment]
This is the intended behavior. Closing
